### ISSUE TITLE
Wording issues?

### ISSUE THREAD

**Issue by maralorn** [shapr/hlsexamples#1]
https://github.com/shapr/hlsexamples/blob/2b69b82abb475882b6dfe2538d705da64704ed00/src/Examples.hs#L6-L8

I think those are code actions not code lenses.

There is also a code lens to make the imports on that line explicit.

**Comment by maralorn** [comment]
I realize the words lens and code action are a bit mixed up in the whole file.

**Comment by shapr** [comment]
I'm torn between accurately describing a code lens vs a code action, or instead removing all references to lens/action and just saying "you should see these choices". What do you think?

**Comment by maralorn** [comment]
I think making this simple and not obfuscating with informations which a lot of users probably don‘t need should be a priority.

Maybe you can add the following comment at the start or the end:
```haskell
-- Note: The different options here are exposed as "code actions" and "code lenses" via the language server protocol. If you have trouble applying some of these examples make sure your editor is configured to use both functionalities and make yourself familiar with how to use them. (e.g. keybindings).
```

**Comment by shapr** [comment]
Good suggestion, I'll do that.
